-- ==============================================================================
-- SUPABASE MIGRATION: ADMIN FEATURES & CRON CONTROLS
-- ==============================================================================
-- Tables created/modified:
-- 1. `postponed_draws`: Tracks dates when draws are postponed/cancelled and cron is disabled.
-- 2. `cron_logs`: Logs cron execution history, skip reasons, and durations.
-- 3. `lotteries`: Extended to support bumper lotteries, jackpot amounts, ticket prices, etc.
-- 4. `app_config`: Seeded with cron controls (cron_enabled, etc.).
-- ==============================================================================

-- 1. Create Postponed Draws Table
CREATE TABLE IF NOT EXISTS public.postponed_draws (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draw_date DATE NOT NULL,
    lottery_code TEXT NOT NULL DEFAULT 'ALL',
    status TEXT NOT NULL DEFAULT 'postponed', -- 'postponed' | 'cancelled' | 'no_draw' | 'holiday'
    reason TEXT NOT NULL,
    rescheduled_date DATE,
    disable_cron BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_postponed_date_lottery UNIQUE (draw_date, lottery_code)
);

ALTER TABLE public.postponed_draws ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'postponed_draws' AND policyname = 'Allow public read access on postponed_draws'
    ) THEN
        CREATE POLICY "Allow public read access on postponed_draws" ON public.postponed_draws FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'postponed_draws' AND policyname = 'Allow public full access on postponed_draws'
    ) THEN
        CREATE POLICY "Allow public full access on postponed_draws" ON public.postponed_draws FOR ALL USING (true);
    END IF;
END $$;

-- 2. Create Cron Logs Table
CREATE TABLE IF NOT EXISTS public.cron_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_time TIMESTAMPTZ DEFAULT NOW(),
    trigger_source TEXT NOT NULL DEFAULT 'cron', -- 'cron' | 'admin_manual' | 'pg_cron'
    status TEXT NOT NULL, -- 'success' | 'skipped' | 'failed'
    message TEXT NOT NULL,
    details JSONB DEFAULT '{}'::jsonb,
    duration_ms INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cron_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'cron_logs' AND policyname = 'Allow public read access on cron_logs'
    ) THEN
        CREATE POLICY "Allow public read access on cron_logs" ON public.cron_logs FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'cron_logs' AND policyname = 'Allow public insert on cron_logs'
    ) THEN
        CREATE POLICY "Allow public insert on cron_logs" ON public.cron_logs FOR INSERT WITH CHECK (true);
    END IF;
END $$;

-- 3. Extend Lotteries Table for Bumper Support
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lotteries' AND column_name = 'is_bumper') THEN
        ALTER TABLE public.lotteries ADD COLUMN is_bumper BOOLEAN DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lotteries' AND column_name = 'jackpot') THEN
        ALTER TABLE public.lotteries ADD COLUMN jackpot TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lotteries' AND column_name = 'ticket_price') THEN
        ALTER TABLE public.lotteries ADD COLUMN ticket_price TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lotteries' AND column_name = 'draw_date') THEN
        ALTER TABLE public.lotteries ADD COLUMN draw_date DATE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'lotteries' AND column_name = 'draw_season') THEN
        ALTER TABLE public.lotteries ADD COLUMN draw_season TEXT;
    END IF;
END $$;

-- 4. Seed Bumper Lotteries into `lotteries` Table
INSERT INTO public.lotteries (day, name, name_ml, code, draw_time, is_bumper, jackpot, ticket_price, draw_season)
VALUES
  ('Bumper (January)', 'Christmas New Year Bumper', 'ക്രിസ്മസ് ന്യൂ ഇയർ ബംപർ', 'XN', '2:00 PM', true, '₹20 Crore', '₹400', 'January'),
  ('Bumper (March)', 'Summer Bumper', 'സമ്മർ ബംപർ', 'SB', '2:00 PM', true, '₹10 Crore', '₹250', 'March (Summer)'),
  ('Bumper (May)', 'Vishu Bumper', 'വിഷു ബംപർ', 'VB', '2:00 PM', true, '₹12 Crore', '₹300', 'May (Vishu)'),
  ('Bumper (July)', 'Monsoon Bumper', 'മൺസൂൺ ബംപർ', 'MB', '2:00 PM', true, '₹10 Crore', '₹250', 'July (Monsoon)'),
  ('Bumper (September)', 'Thiruvonam Bumper', 'തിരുവോണം ബംപർ', 'TH', '2:00 PM', true, '₹25 Crore', '₹500', 'September (Onam)'),
  ('Bumper (November)', 'Pooja Bumper', 'പൂജ ബംപർ', 'PB', '2:00 PM', true, '₹12 Crore', '₹300', 'November (Pooja/Diwali)')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  name_ml = EXCLUDED.name_ml,
  day = EXCLUDED.day,
  draw_time = EXCLUDED.draw_time,
  is_bumper = EXCLUDED.is_bumper,
  jackpot = EXCLUDED.jackpot,
  ticket_price = EXCLUDED.ticket_price,
  draw_season = EXCLUDED.draw_season;

-- 5. Seed Cron Configuration in `app_config` & Grant Update Permissions
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'app_config' AND policyname = 'Allow public full access on app_config'
    ) THEN
        CREATE POLICY "Allow public full access on app_config" ON public.app_config FOR ALL USING (true);
    END IF;
END $$;

INSERT INTO public.app_config (key, value)
VALUES 
  ('cron_enabled', 'true'),
  ('cron_start_time', '15:00'),
  ('cron_end_time', '17:00'),
  ('cron_bumper_start_time', '14:00'),
  ('cron_bumper_end_time', '18:00'),
  ('cron_frequency_mins', '3')
ON CONFLICT (key) DO NOTHING;



