-- Supabase Database Schema Migration
-- Copy & Run this SQL in the Supabase SQL Editor (https://supabase.com/dashboard/project/dqsoseefmiwyjkgqmphh/sql)

-- 1. Create Lotteries Master Table
CREATE TABLE IF NOT EXISTS public.lotteries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  name_ml TEXT,
  code TEXT UNIQUE NOT NULL,
  draw_time TEXT DEFAULT '3:00 PM',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Draw Results Table
CREATE TABLE IF NOT EXISTS public.draw_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  draw_date DATE NOT NULL,
  draw_name TEXT NOT NULL,
  draw_code TEXT NOT NULL,
  lottery_code TEXT NOT NULL,
  first_prize JSONB NOT NULL DEFAULT '{}'::jsonb,
  prizes JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_draw_date_lottery UNIQUE (draw_date, lottery_code)
);

-- 3. Enable Row Level Security (RLS) & Public Read Access Policies
ALTER TABLE public.lotteries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.draw_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on lotteries" ON public.lotteries
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert/update on lotteries" ON public.lotteries
  FOR ALL USING (true);

CREATE POLICY "Allow public read access on draw_results" ON public.draw_results
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert/update on draw_results" ON public.draw_results
  FOR ALL USING (true);

-- 4. Enable Realtime Publications on draw_results
ALTER PUBLICATION supabase_realtime ADD TABLE public.draw_results;

-- 5. Seed 7 Weekly Lotteries Master Data
INSERT INTO public.lotteries (day, name, name_ml, code, draw_time)
VALUES
  ('Monday', 'Bhagyathara', 'ഭാഗ്യതാരാ', 'BT', '3:00 PM'),
  ('Tuesday', 'Sthree Sakthi', 'സ്ത്രീശക്തി', 'SS', '3:00 PM'),
  ('Wednesday', 'Dhanalekshmi', 'ധനലക്ഷ്മി', 'DL', '3:00 PM'),
  ('Thursday', 'Karunya Plus', 'കാരുണ്യ പ്ലസ്', 'KN', '3:00 PM'),
  ('Friday', 'Suvarna Keralam', 'സുവർണ്ണ കേരളം', 'SK', '3:00 PM'),
  ('Saturday', 'Karunya', 'കാരുണ്യ', 'KR', '3:00 PM'),
  ('Sunday', 'Samrudhi', 'സമൃദ്ധി', 'SM', '3:00 PM')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  name_ml = EXCLUDED.name_ml,
  day = EXCLUDED.day,
  draw_time = EXCLUDED.draw_time;

-- 6. Dynamic App Configuration Table (Allows easy URL changes in the future)
CREATE TABLE IF NOT EXISTS public.app_config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on app_config" ON public.app_config
  FOR SELECT USING (true);

INSERT INTO public.app_config (key, value)
VALUES 
  ('app_url', 'https://lottry-fawn.vercel.app'),
  ('cron_secret', 'kerala_lottery_cron_secret_2026')
ON CONFLICT (key) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = NOW();

-- 7. Supabase pg_cron Setup
-- For setting up automated lottery sync schedules (Every 2.5 mins between 3:00-4:00 PM IST & Every 5 mins between 4:00-5:00 PM IST),
-- see the dedicated script: supabase/cron_setup.sql

